remote_theme: pages-themes/primer
plugins:
- jekyll-remote-theme

title: "Computer Science Courses"
description: "Course materials for CS classes"

# Build settings
markdown: kramdown
highlighter: rouge

# Default layout
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
