remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

title: "Computer Science Courses"
description: "Course materials for CS classes"

baseurl: "/courses"

# Build settings
markdown: kramdown
highlighter: rouge

# Just the Docs specific settings
color_scheme: dark
search_enabled: true
heading_anchors: true


# Default layout
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"